### ISSUE TITLE
feat: extend json and yaml support

### ISSUE THREAD

**Issue by kekavc24** [kekavc24/magical_version_bump#42]
**Description**

Partial support for JSON was added after #28 was closed. However, key differences and similarities exist in both, with each having its strengths. It would be great to extend and support that

**Requirements**

- [x] #45

```json

  {
      "key" : [ "normal", ["nested"] ]
  }

 ```

- [x] #44

```json

 {
      "key" : [  "normal value", {"nested" : "map"}, "another value" ]
  }

```

In Yaml, a nested list would need to be linked to another key. So any list would technically be incorporated to the nearest key.

```yaml

key:
    - normal value
    
     # a nested map in list in yaml
    - nested: map
      another key: value

    - another value
    
    # a nested list linked to a key
    - nested-list:
        - nested value
        - another value

```
